# Generated by Django 5.2.1 on 2025-07-13 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_document_description_document_title_topic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="description",
        ),
        migrations.RemoveField(
            model_name="document",
            name="title",
        ),
        migrations.RemoveField(
            model_name="propertyimage",
            name="topic",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="name",
        ),
        migrations.AddField(
            model_name="topic",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="document",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="core.property",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="core.property",
            ),
        ),
        migrations.AlterField(
            model_name="propertyimage",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="core.property",
            ),
        ),
    ]
