# Generated by Django 5.2.1 on 2025-07-15 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_document_description_remove_document_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="topic",
        ),
        migrations.RemoveField(
            model_name="note",
            name="topic",
        ),
        migrations.AlterField(
            model_name="document",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="core.property",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="core.property",
            ),
        ),
        migrations.AlterField(
            model_name="propertyimage",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="core.property",
            ),
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="core.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "section",
                "verbose_name_plural": "sections",
            },
        ),
        migrations.AddField(
            model_name="document",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="core.section",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="core.section",
            ),
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
