# Generated by Django 5.2.1 on 2025-07-15 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_document_topic_remove_note_topic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="core.property",
            ),
        ),
    ]
