# Generated by Django 5.2.1 on 2025-07-17 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_document_property"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyimage",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="core.section",
            ),
        ),
    ]
